[platformio]
default_envs = thing_plus_base

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

; Target: SparkFun Thing Plus ESP32 (Base Station)
[env:thing_plus_base]
board = esp32thing_plus
build_src_filter = -<*> +<base_station/*>
; upload_port = COM3      ; or /dev/ttyUSB0

; Target: Transmitter Shield 1
[env:shield_tx0]
board = esp32dev
build_flags = -DSENDER_ID=0
build_src_filter = -<*> +<transmitters/*>
; upload_port = COM4

; Target: Transmitter Shield 2
[env:shield_tx1]
board = esp32dev
build_flags = -DSENDER_ID=1
build_src_filter = -<*> +<transmitters/*>
; upload_port = COM5