-- ============================================================================
-- Write access for the app: a signed-in user may create / edit / delete ONLY
-- their own sessions and the sets that belong to those sessions.
-- (demo_read_access.sql already covers reads.)  Safe to re-run.
-- Run in Supabase → SQL Editor.
-- ============================================================================
alter table public.sessions enable row level security;
alter table public.sets     enable row level security;

drop policy if exists "own sessions insert" on public.sessions;
drop policy if exists "own sessions update" on public.sessions;
drop policy if exists "own sessions delete" on public.sessions;

create policy "own sessions insert" on public.sessions
  for insert to authenticated with check (athlete_id = auth.uid());
create policy "own sessions update" on public.sessions
  for update to authenticated using (athlete_id = auth.uid()) with check (athlete_id = auth.uid());
create policy "own sessions delete" on public.sessions
  for delete to authenticated using (athlete_id = auth.uid());

drop policy if exists "own sets insert" on public.sets;
drop policy if exists "own sets update" on public.sets;
drop policy if exists "own sets delete" on public.sets;

create policy "own sets insert" on public.sets
  for insert to authenticated
  with check (exists (select 1 from public.sessions s where s.id = session_id and s.athlete_id = auth.uid()));
create policy "own sets update" on public.sets
  for update to authenticated
  using      (exists (select 1 from public.sessions s where s.id = session_id and s.athlete_id = auth.uid()))
  with check (exists (select 1 from public.sessions s where s.id = session_id and s.athlete_id = auth.uid()));
create policy "own sets delete" on public.sets
  for delete to authenticated
  using (exists (select 1 from public.sessions s where s.id = session_id and s.athlete_id = auth.uid()));

-- Sessions/sets ids are generated by the database when the app omits them.
alter table public.sessions alter column id set default gen_random_uuid();
alter table public.sets     alter column id set default gen_random_uuid();
